apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"  # 👈 always use "latest"
  local:
    push: false
  artifacts:
    - image: zhbdripon/ticketingauth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: zhbdripon/ticketingclient
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.{ts,tsx}'
            dest: .
    - image: zhbdripon/ticketingtickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
